name: Mirror to Subdomain Repo

on: [push]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolution/mirror-action@master
        with:
          # This is the URL of your SECOND (mirror) repository
          target_repo_url:
            https://github.com/entouss/toolboard-mirror.git
          # This uses the secret you created in Step 2
          github_token: ${{ secrets.MIRROR_TOKEN }}